### PR TITLE
Add hu (Hungarian - magyar) locale

### PR DESCRIPTION
**Pull request by ovari**
Does another file need updating to enable Hungarian?

Thank you

### CODE REVIEW

**Comment by ovari** [comment]
@joeattardi does another file need updating to enable Hungarian? Thank you

**Comment by ovari** [comment]
@joeattardi can you please merge this? If not, please advise what else is required to merge. If not required, please advise so this can be deleted. Thank you

**Comment by joeattardi** [comment]
The ellipsis changes don't seem necessary here, the `…` character isn't widely used, at least not in English. I am happy to merge the `hu` language pack but please revert the ellipsis changes.

**Comment by ovari** [comment]
Mozilla (eg Firefox and Thunderbird) use 1-character ellipses.
https://transvision.mozfr.org/?recherche=Browse%E2%80%A6&repo=all_projects&sourcelocale=en-US&locale=en-GB&search_type=strings&entire_string=entire_string

**Comment by ovari** [comment]
@joeattardi thank you for your comment. As you requested, ellipses should be now 3-character dots. Can you please now merge? Thank you

**Comment by ovari** [comment]
Ellipses have been reverted to 3-character ellipses (except for Hungarian) at https://github.com/joeattardi/picmo/pull/282/files.

Do you also require Hungarian to have a 3-character ellipsis to enable merging?

Thank you

**Comment by ovari** [comment]
Thank you @joeattardi

**Comment by ovari** [comment]
@joeattardi please advise if there are any new translations required in the future. Thank you

**Pull request merged**
